version: '3'

services:

  pipeline:
    image: ldynia/pipeline:1.0
    build: docker/ubuntu
    restart: always
    hostname: pipeline
    container_name: pipeline
    command: bash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh
      - ./app:/app
      - ./data:/pipeline/data
      - ./results:/pipeline/results
    environment:
      DOCKER_COMPOSE: 'true'

  codons:
    image: ldynia/codon:1.0
    build: pipes/codon-counter
    restart: always
    hostname: codon
    container_name: codon
    command: ash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh
      - ./data:/pipeline/data
      - ./results:/pipeline/results

  nucleotides:
    image: ldynia/nucleotide:1.0
    build: pipes/nucleotide-counter
    restart: always
    hostname: nucleotide
    container_name: nucleotide
    command: bash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh
      - ./data:/pipeline/data
      - ./results:/pipeline/results

volumes:
  ssh:
  results:
