version: '3'

services:

  pipeline:
    image: ldynia/pipeline:1.0
    build: docker/ubuntu
    restart: always
    hostname: pipeline
    container_name: pipeline
    command: bash /docker/startup.sh

  codons:
    image: ldynia/codon:1.0
    build: pipes/codon-counter
    restart: always
    hostname: codon
    container_name: codon
    command: sh /app/scripts/startup.sh

  nucleotides:
    image: ldynia/nucleotide:1.0
    build: pipes/nucleotide-counter
    restart: always
    hostname: nucleotide
    container_name: nucleotide
    command: sh /app/scripts/startup.sh
