version: '3'

services:

  pipeline:
    image: ldynia/pipeline:1.0
    build: docker/ubuntu
    restart: always
    hostname: pipeline
    container_name: pipeline
    command: bash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh
    environment:
      # container names
      PIPES: "codon,nucleotide"
      DOCKER_COMPOSE: 'true'

  codons:
    image: ldynia/codon:1.0
    build: pipes/codon-counter
    restart: always
    hostname: codon
    container_name: codon
    command: bash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh

  nucleotides:
    image: ldynia/nucleotide:1.0
    build: pipes/nucleotide-counter
    restart: always
    hostname: nucleotide
    container_name: nucleotide
    command: bash /docker/startup.sh
    volumes:
      - ssh:/root/.ssh

volumes:
  ssh:
