rule codon:
    input:
        "/pipeline/data/dna.fsa"
    output:
        "/pipeline/results/cdncount.json.out"
    # script:
    #     "scripts/codon.py"
    shell:
        "ssh codon cdncount -f {input} > {output}"

rule nucleotide:
    input:
        "/pipeline/data/dna.fsa"
    output:
        "/pipeline/results/ntcount.json.out"
    # script:
    #     "scripts/nucleotide.py"
    shell:
        "ssh nucleotide ntcount -f {input} > {output}"
